<a href="https://colab.research.google.com/github/AtulMomre2327/Intro-to-Machine-Learning/blob/main/DecisionTreeClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
from  sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [29]:
df = pd.read_csv('/content/drive/MyDrive/Data  Set/Copy of daily_weather.csv')

In [30]:
df.head()

   air_pressure_9am  air_temp_9am  ...  relative_humidity_9am  high_humidity_3pm
0        918.060000     74.822000  ...              42.420000                  1
1        917.347688     71.403843  ...              24.328697                  0
2        923.040000     60.638000  ...               8.900000                  0
3        920.502751     70.138895  ...              12.189102                  0
4        921.160000     44.294000  ...              92.410000                  1

[5 rows x 10 columns]

In [31]:
df.isnull().sum()

air_pressure_9am          3
air_temp_9am              5
avg_wind_direction_9am    4
avg_wind_speed_9am        3
max_wind_direction_9am    3
max_wind_speed_9am        4
rain_accumulation_9am     6
rain_duration_9am         3
relative_humidity_9am     0
high_humidity_3pm         0
dtype: int64

In [32]:
df.dropna(inplace=True)

In [34]:
x = df.drop(['high_humidity_3pm'],axis=1)
y = df['high_humidity_3pm']

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [37]:
model = DecisionTreeClassifier()

In [38]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [39]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [40]:
print('Train ACC :-', accuracy_score(y_train, train_pred))
print('Test ACC :-', accuracy_score(y_test, test_pred))

Train ACC :- 1.0
Test ACC :- 0.863849765258216