<a href="https://colab.research.google.com/github/AtulMomre2327/Intro-to-Machine-Learning/blob/main/DecisionTreeClassifier_data_set_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Data  Set/gender_classification_v7.csv')

In [6]:
df.head()

   long_hair  forehead_width_cm  ...  distance_nose_to_lip_long  gender
0          1               11.8  ...                          1    Male
1          0               14.0  ...                          0  Female
2          0               11.8  ...                          1    Male
3          0               14.4  ...                          1    Male
4          1               13.5  ...                          0  Female

[5 rows x 8 columns]

In [8]:
df.isnull().sum()

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [9]:
df['gender'] = df['gender'].map({'Male':0,'Female':1})

In [10]:
x = df.drop('gender',axis=1)
y = df['gender']

In [11]:
x.head(1)

   long_hair  forehead_width_cm  ...  lips_thin  distance_nose_to_lip_long
0          1               11.8  ...          1                          1

[1 rows x 7 columns]

In [12]:
y.head(1)

0    0
Name: gender, dtype: int64

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
model = DecisionTreeClassifier()

In [15]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [16]:
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

In [17]:
print('Training Accuracy:',accuracy_score(y_train,train_pred))
print('Testing Accuracy:',accuracy_score(y_test,test_pred))
#

Training Accuracy: 0.99825
Testing Accuracy: 0.9530469530469531