<a href="https://colab.research.google.com/github/AtulMore2327/Intro-to-Machine-Learning/blob/main/deep%20learning_Regression_Model_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install tensorflow
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.82.1)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data  Set/Manufacturing_dataset.csv')
df.head()

,Timestamp,Temperature (°C),Machine Speed (RPM),Production Quality Score,Vibration Level (mm/s),Energy Consumption (kWh),Optimal Conditions
0,2025-04-01 08:00:00,78.92,1461,8.49,0.07,1.97,0
1,2025-04-01 08:01:00,71.83,1549,8.97,0.04,1.01,0
2,2025-04-01 08:02:00,74.88,1498,8.52,0.08,1.60,0
3,2025-04-01 08:03:00,77.27,1478,8.28,0.09,1.87,0
4,2025-04-01 08:04:00,76.50,1524,8.07,0.04,1.53,0

In [ ]:
df.shape

(10000, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Timestamp                 10000 non-null  object
 1   Temperature (°C)          10000 non-null  float64
 2   Machine Speed (RPM)       10000 non-null  int64
 3   Production Quality Score  10000 non-null  float64
 4   Vibration Level (mm/s)    10000 non-null  float64
 5   Energy Consumption (kWh)  10000 non-null  float64
 6   Optimal Conditions        10000 non-null  int64
dtypes: float64(4), int64(2), object(1)
memory usage: 547.0+ KB

In [ ]:
df['Production Quality Score'].value_counts()

Production Quality Score
8.15    133
8.57    127
8.44    125
8.69    122
8.64    118
       ...
8.72     81
8.95     78
8.17     76
8.00     51
9.00     47
Name: count, Length: 101, dtype: int64

In [ ]:
df.head()

,Timestamp,Temperature (°C),Machine Speed (RPM),Production Quality Score,Vibration Level (mm/s),Energy Consumption (kWh),Optimal Conditions
0,2025-04-01 08:00:00,78.92,1461,8.49,0.07,1.97,0
1,2025-04-01 08:01:00,71.83,1549,8.97,0.04,1.01,0
2,2025-04-01 08:02:00,74.88,1498,8.52,0.08,1.60,0
3,2025-04-01 08:03:00,77.27,1478,8.28,0.09,1.87,0
4,2025-04-01 08:04:00,76.50,1524,8.07,0.04,1.53,0

In [ ]:
# df = pd.get_dummies(df,columns= ['Timestamp'])

In [ ]:
df = df.drop(columns=['Timestamp'])

In [ ]:
df.head()

,Temperature (°C),Machine Speed (RPM),Production Quality Score,Vibration Level (mm/s),Energy Consumption (kWh),Optimal Conditions
0,78.92,1461,8.49,0.07,1.97,0
1,71.83,1549,8.97,0.04,1.01,0
2,74.88,1498,8.52,0.08,1.60,0
3,77.27,1478,8.28,0.09,1.87,0
4,76.50,1524,8.07,0.04,1.53,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Temperature (°C)          10000 non-null  float64
 1   Machine Speed (RPM)       10000 non-null  int64
 2   Production Quality Score  10000 non-null  float64
 3   Vibration Level (mm/s)    10000 non-null  float64
 4   Energy Consumption (kWh)  10000 non-null  float64
 5   Optimal Conditions        10000 non-null  int64
dtypes: float64(4), int64(2)
memory usage: 468.9 KB

In [ ]:
x = df.drop(columns=['Production Quality Score','Optimal Conditions'])
y = df['Production Quality Score']

In [ ]:
x.head()

,Temperature (°C),Machine Speed (RPM),Vibration Level (mm/s),Energy Consumption (kWh)
0,78.92,1461,0.07,1.97
1,71.83,1549,0.04,1.01
2,74.88,1498,0.08,1.60
3,77.27,1478,0.09,1.87
4,76.50,1524,0.04,1.53

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
x_train.shape

(8000, 4)

In [ ]:
model = Sequential()
model.add(Dense(5,activation = 'relu',input_dim = 4))
model.add(Dense(10,activation = 'relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(1))
#

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 10)             │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 15)             │           165 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 20)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 596 (2.33 KB)

 Trainable params: 596 (2.33 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='mean_squared_error', optimizer='Adam', metrics=['mean_absolute_error'])

In [ ]:
model.compile(loss='mean_squared_error', optimizer='Adam', metrics=['mean_absolute_error'])
model.fit(x_train,y_train,batch_size=10,epochs=10,validation_split=0.2)

Epoch 1/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.3320 - mean_absolute_error: 2.0185 - val_loss: 0.1748 - val_mean_absolute_error: 0.3309
Epoch 2/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1262 - mean_absolute_error: 0.2915 - val_loss: 0.0951 - val_mean_absolute_error: 0.2579
Epoch 3/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0933 - mean_absolute_error: 0.2594 - val_loss: 0.0851 - val_mean_absolute_error: 0.2489
Epoch 4/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0896 - mean_absolute_error: 0.2552 - val_loss: 0.0884 - val_mean_absolute_error: 0.2537
Epoch 5/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0910 - mean_absolute_error: 0.2575 - val_loss: 0.0878 - val_mean_absolute_error: 0.2524
Epoch 6/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0897 - mean_absolute_error: 0.2568 - val_loss: 0.0873 - val_mean_absolute_error: 0.2515
Epoch 7/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0913 - mean_absolute_error: 0.2580 - val_loss: 0.0851 - val_mean_absolute_error: 0.2499
Epoch 8/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0893 - mean_absolute_error: 0.2561 - val_loss: 0.0869 - val_mean_absolute_error: 0.2517
Epoch 9/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0896 - mean_absolute_error: 0.2550 - val_loss: 0.0833 - val_mean_absolute_error: 0.2477
Epoch 10/10
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0919 - mean_absolute_error: 0.2596 - val_loss: 0.0829 - val_mean_absolute_error: 0.2469

In [ ]:
train_pred = model.predict(x_train)
# train_pred = np.where(train_pred>0.5,1,0)
train_pred

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step

array([[8.494286],
       [8.486657],
       [8.486226],
       ...,
       [8.526061],
       [8.549973],
       [8.487671]], dtype=float32)

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_train,train_pred)

0.2494593579816818

In [ ]:
test_pred = model.predict(x_test)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,test_pred)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step

0.25078529270172123